version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  #image name because it is built first
  node-app:
   build:         
      context: .
      args:
        - NODE_ENV=production
   environment:
     - NODE_ENV=production 
     - MONGO_USER=root
     - MONGO_PASSWORD=root
   command: node app.js  

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root