version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  #image name because it is built first
  node-app:
   build:         
      context: .
      args:
        - NODE_ENV=production
   environment:
     - NODE_ENV=production 
   command: node app.js  